### PR TITLE
First version for calculating the transition matrix elements between …

### PR DESCRIPTION
**Pull request by fmoramore**
…bound states.

It only works for transitions between M=0 states, and the filename is fixed.

### CODE REVIEW

**Comment by serguei-patchkovskii** [comment]
Some comments:

1. Variable wt_tme breaks naming conventions: all variables with the prefix wt_ are expected to be imported from wavefunction_tools.f90

2. The code segment:

`    if (wt_tme.and.wt_enable_memory_caches(1).and.(cap_name=="none")) then
      call wt_transition_matrix_elements(wt_tme,iu_tme)
      else
          stop 'spherical_tdse%input_error - wt_tme'
    end if                 `

contains a logic error - if transition matrix elements are not calculated, it crashes the program.

3. subroutine wt_transition_matrix_elements duplicated code for the internal subroutines in wt_dipole. Since these are used in more than one place now, they should be made module subroutines, and called from both places.

Otherwise, it's good.

**Comment by fmoramore** [comment]
1. I will move it to wavefuction_tools.f90 then
2. And also move the logic here
3. I will make them subroutines in wavefunction_tools.f90 then!
Will re-commit as soon as possible

**Comment by serguei-patchkovskii** [comment]
I've made some style changes and added a functioning test case. I've also modified the output format to include state energies (because I assume you need them anyways).
Please check whether anything got broken in the process!

**Comment by fmoramore** [comment]
Changes are perfect! I think it is ready to be merged.

**Review by serguei-patchkovskii — APPROVED** [review]

**Pull request merged**
